#8 Over Engineered Main View
chan-kelv/parkR pull request #21
Opened 2019-09-23 01:16 UTC by chan-kelv

2019-09-23 03:38 UTC, frostyshadows requested changes
Weeee LiveData. Left some comments about minor stylistic/naming things.

2019-09-23 03:38 UTC, frostyshadows commented on app/src/main/java/com/kelvin/parkr/ui/DashboardFragment.kt
> +        return view
could you just return `inflater.inflate(R.layout.fragment_dashboard, container, false)`?

2019-09-23 03:38 UTC, frostyshadows commented on app/src/main/java/com/kelvin/parkr/ui/DashboardFragment.kt
> +        dashboardPagerAdapter = DashboardPagerAdapter(childFragmentManager)
Unless we're gonna do anything else to the dashboardPagerAdapter later, could combine these two lines into `pager_dashboard.adapter = DashboardPagerAdapter(childFragmentManager)`

2019-09-23 03:38 UTC, frostyshadows commented on app/src/main/java/com/kelvin/parkr/ui/ParkNowFragment.kt
> +class ParkNowFragment : BasePagerFragment("Park Now", R.drawable.ic_car) {
"Park Now" could be declared a `const val` above the class so that it's not a magic String and can be reused.

2019-09-23 03:38 UTC, frostyshadows commented on app/src/main/java/com/kelvin/parkr/ui/ParkingInProgressFragment.kt
> +class ParkingInProgressFragment : BasePagerFragment("In Progress", R.drawable.ic_parking) {
"In Progress" can also be a constant

2019-09-23 03:38 UTC, frostyshadows commented on app/src/main/java/com/kelvin/parkr/ui/adapter/DashboardPagerAdapter.kt
> +    fun refreshPagerFragments(fragments: List<BasePagerFragment>) {
I think `setPagerFragments()` or `replacePagerFragments()` or `updatePagerFragments()` would be a more accurate name here.

2019-09-23 03:38 UTC, frostyshadows commented on app/src/main/java/com/kelvin/parkr/viewModel/DashboardViewModel.kt
> +    fun addPagerFragments(fragments: MutableList<BasePagerFragment>) {
isn't this more like `setPagerFragments()` than `addPagerFragments()`

2019-09-23 03:38 UTC, frostyshadows commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/toolbar_main" app:layout_constraintStart_toStartOf="parent"
can the different `app:layout_`s all go on their own lines?

2019-09-23 03:38 UTC, frostyshadows commented on app/src/main/res/layout/fragment_dashboard.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
this XML formatting looks a bit weird to me, maybe try running the formatter in Android Studio again.

2019-09-23 03:38 UTC, frostyshadows commented on app/src/test/java/com/kelvin/parkr/DashboardVMTest.kt
> +class DashboardVMTest {
yay tests

2019-09-23 03:38 UTC, frostyshadows commented on app/src/main/java/com/kelvin/parkr/ui/BaseActivity.kt
> +    protected var mCurrentVisibleFragment: Fragment? = null
I think prefixing variables with `m`'s more of a Java thing, calling it `currentVisibleFragment` would be more Kotlin-y

2019-09-23 09:28 UTC, chan-kelv commented on app/src/main/java/com/kelvin/parkr/ui/BaseActivity.kt
> +    protected var mCurrentVisibleFragment: Fragment? = null
Both the founder of the Hungarian notation https://beust.com/weblog/2017/07/17/i-am-the-reason-for-hungarian-notation-in-android/ and Jake https://jakewharton.com/just-say-no-to-hungarian-notation/ are making a case against the notation. We even ripped it out of work :p

2019-09-27 21:27 UTC, chan-kelv commented on app/build.gradle
> +        unitTests.includeAndroidResources = true
add comment as to what this does

2019-10-06 21:43 UTC, frostyshadows approved these changes
one suggestion, otherwise LGTM!

2019-10-06 21:43 UTC, frostyshadows commented on app/src/main/java/com/kelvin/parkr/ui/DashboardFragment.kt
> +    private lateinit var dashboardVm: DashboardViewModel
could we name this `dashboardViewModel` instead? Since in software engineering it could also mean virtual memory.

2019-10-07 01:27 UTC, merged